workflows:
  android_release:
    name: Android Release Workflow
    triggering:
      events:
        - push
    environment:
      vars:
        # These should be created as Secret variables in the CM UI
        KEYSTORE_PASSWORD: Encrypted(KEYSTORE_PASSWORD)
        KEY_ALIAS: storeuploader
        KEY_PASSWORD: Encrypted(KEY_PASSWORD)
    scripts:
      - name: Install Cordova
        script: |
          npm install -g cordova
      - name: Add Android platform
        script: |
          cordova platform add android --no-fetch
      - name: Build Release APK
        script: |
          cordova build android --release
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
